package com.hemju.threadmill.soak.harness.endurance;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

import com.hemju.threadmill.soak.harness.endurance.EnduranceMain.ChildRun;

/**
 * Collation of the per-backend {@code summary.json} files into one
 * {@code endurance-summary.json} / {@code endurance-summary.md} pair at the
 * top of the run directory — the first thing an operator (or an AI agent
 * handed the directory) should read. The per-backend artifacts stay the
 * source of truth; this file answers "did both backends pass, and how did
 * they compare?".
 *
 * <p>The combined verdict is {@code passed} only when every child exited 0
 * <em>and</em> reported a {@code passed} verdict; a child that died without
 * writing a summary is reported as {@code missing-summary} and fails the run.
 */
final class EnduranceSummary {

    private final String runId;
    private final String scenario;
    private final String verdict;
    private final long wallClockMs;
    private final List<BackendOutcome> outcomes;

    private EnduranceSummary(
            String runId, String scenario, String verdict, long wallClockMs, List<BackendOutcome> outcomes) {
        this.runId = runId;
        this.scenario = scenario;
        this.verdict = verdict;
        this.wallClockMs = wallClockMs;
        this.outcomes = outcomes;
    }

    String verdict() {
        return verdict;
    }

    static EnduranceSummary collate(EnduranceConfig config, List<ChildRun> children, Instant startedAt) {
        var mapper = new ObjectMapper();
        var outcomes = new ArrayList<BackendOutcome>();
        boolean allPassed = true;
        for (ChildRun child : children) {
            BackendOutcome outcome = BackendOutcome.of(mapper, child);
            allPassed &= outcome.passed();
            outcomes.add(outcome);
        }
        return new EnduranceSummary(
                config.runId(),
                config.scenario(),
                allPassed ? "passed" : "failed",
                Duration.between(startedAt, Instant.now()).toMillis(),
                outcomes);
    }

    void write(Path outputDir) throws IOException {
        var mapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
        Map<String, Object> doc = new LinkedHashMap<>();
        doc.put("runId", runId);
        doc.put("scenario", scenario);
        doc.put("verdict", verdict);
        doc.put("wallClockMs", wallClockMs);
        Map<String, Object> backends = new LinkedHashMap<>();
        for (BackendOutcome outcome : outcomes) {
            backends.put(outcome.label, outcome.asMap());
        }
        doc.put("backends", backends);
        doc.put(
                "notes",
                List.of("Generated by the threadmill-soak endurance orchestrator."
                        + " Per-backend artifacts (trace.jsonl, invariants.json, summary.json) live in the"
                        + " subdirectories; drop this whole directory into an AI agent to analyse."));
        Files.writeString(
                outputDir.resolve("endurance-summary.json"), mapper.writeValueAsString(doc), StandardCharsets.UTF_8);
        Files.writeString(outputDir.resolve("endurance-summary.md"), renderMarkdown(), StandardCharsets.UTF_8);
    }

    private String renderMarkdown() {
        var sb = new StringBuilder();
        sb.append("# Endurance run summary\n\n");
        sb.append("- **Run id:** `").append(runId).append("`\n");
        sb.append("- **Scenario:** `").append(scenario).append("`\n");
        sb.append("- **Wall clock:** ")
                .append(Duration.ofMillis(wallClockMs).toMinutes())
                .append(" min\n");
        sb.append("- **Verdict:** **").append(verdict).append("**\n\n");
        sb.append("| Backend | Verdict | Exit | Enqueued | Succeeded | Failed | Retried | Jobs/sec | e2e p99 (ms) |"
                + " Failed invariants |\n");
        sb.append("|---|---|---|---|---|---|---|---|---|---|\n");
        for (BackendOutcome o : outcomes) {
            sb.append("| `").append(o.label).append("` | ");
            sb.append("passed".equals(o.verdict) ? "passed" : "**" + o.verdict + "**")
                    .append(" | ");
            sb.append(o.exitCode).append(" | ");
            sb.append(o.enqueued).append(" | ");
            sb.append(o.succeeded).append(" | ");
            sb.append(o.failed).append(" | ");
            sb.append(o.retried).append(" | ");
            sb.append(String.format("%.1f", o.throughput)).append(" | ");
            sb.append(o.endToEndP99Ms).append(" | ");
            sb.append(o.failedInvariants.isEmpty() ? "—" : String.join(", ", o.failedInvariants))
                    .append(" |\n");
        }
        sb.append("\nBoth stacks shared one machine: throughput and latency are comparable to each other under"
                + " equal contention, not absolute capacity figures.\n");
        return sb.toString();
    }

    private record BackendOutcome(
            String label,
            String backend,
            int exitCode,
            String verdict,
            long enqueued,
            long succeeded,
            long failed,
            long timedOut,
            long quarantined,
            long retried,
            double throughput,
            long endToEndP99Ms,
            List<String> failedInvariants,
            String outputDir) {

        boolean passed() {
            return exitCode == 0 && "passed".equals(verdict);
        }

        static BackendOutcome of(ObjectMapper mapper, ChildRun child) {
            int exitCode = child.process.isAlive() ? -1 : child.process.exitValue();
            Optional<JsonNode> summary = EnduranceMain.readJson(mapper, child.outputDir.resolve("summary.json"));
            if (summary.isEmpty()) {
                return new BackendOutcome(
                        child.label,
                        child.backend,
                        exitCode,
                        "missing-summary",
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0.0,
                        0,
                        List.of(),
                        child.outputDir.toString());
            }
            JsonNode s = summary.get();
            JsonNode perf = s.path("performance");
            var failedInvariants = new ArrayList<String>();
            for (JsonNode inv : s.path("invariants")) {
                if (!inv.path("passed").asBoolean(true)) {
                    failedInvariants.add(inv.path("name").asText("?"));
                }
            }
            return new BackendOutcome(
                    child.label,
                    child.backend,
                    exitCode,
                    s.path("verdict").asText("unknown"),
                    perf.path("totalEnqueued").asLong(0),
                    perf.path("totalSucceeded").asLong(0),
                    perf.path("totalFailed").asLong(0),
                    perf.path("totalTimedOut").asLong(0),
                    perf.path("totalQuarantined").asLong(0),
                    perf.path("totalRetried").asLong(0),
                    perf.path("throughputJobsPerSec").path("overall").asDouble(0.0),
                    perf.path("latencyMs").path("endToEnd").path("p99").asLong(0),
                    List.copyOf(failedInvariants),
                    child.outputDir.toString());
        }

        Map<String, Object> asMap() {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("backend", backend);
            m.put("exitCode", exitCode);
            m.put("verdict", verdict);
            m.put("totalEnqueued", enqueued);
            m.put("totalSucceeded", succeeded);
            m.put("totalFailed", failed);
            m.put("totalTimedOut", timedOut);
            m.put("totalQuarantined", quarantined);
            m.put("totalRetried", retried);
            m.put("overallThroughputJobsPerSec", throughput);
            m.put("endToEndP99Ms", endToEndP99Ms);
            m.put("failedInvariants", failedInvariants);
            m.put("outputDir", outputDir);
            return m;
        }
    }
}
